services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_CONN: "postgres://AndreyKataev:Password@db:5432/tender_db?sslmode=disable"
      POSTGRES_JDBC_URL: "jdbc:postgresql://db:5432/tender_db"
      POSTGRES_USERNAME: "AndreyKataev"
      POSTGRES_PASSWORD: "Password"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: "tender_db"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: AndreyKataev
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: tender_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
